### ISSUE TITLE
Adapter terminates very frequent and does not reconnect

### ISSUE THREAD

**Issue by bfelizardo** [ioBroker/ioBroker.nightscout#10]
**Describe the bug**  
The adapter runs and everything is green (connected to host: true; heartbeat: true; connected to nightscout: true). But after a unspecific lap of time the adapter goes red and the adapater terminated by itself.

**To Reproduce**  
1. Go to 'Instances'
2. Hover on 'instance'
3. See status red (connected to host: false; heartbeat: false; connected to nightscout: false)

**Expected behavior**  
The adapter should run permanently. It already worked before. Issue came up since I have updated node.js and js-controller (versions see below)

**Screenshots & Logfiles**  
[log_nightscoutadapter_20210225.txt](https://github.com/ioBroker/ioBroker.nightscout/files/6041453/log_nightscoutadapter_20210225.txt)

**Versions:**  
 - Adapter version: 0.11.5
 - JS-Controller version: 3.2.16
 - Node version: 12.21.0
 - Operating system: ioBroker installed within a docker container on a Synology NAS

**Comment by volkerrichert** [comment]
I have this also since a few week. I'll take a look

**Comment by volkerrichert** [comment]
Ok, i think i found it. iob seems to have an additional test if you try to set an object. Maybe BlueFox knows more about the release

**Comment by bfelizardo** [comment]
Thank you @volkerrichert! 

@GermanBluefox can you help on this issue? The adapter keeps on terminating and I have to restart is everyday. Thanks you in advance!

**Comment by volkerrichert** [comment]
@bfelizardo You can add a restart script to do so. My daughter isn't here at the moment, so i can't see if my fix works. I can push it into my fork and you can try it, if you want.

**Comment by bfelizardo** [comment]
@volkerrichert oh yes please if you can push it in your fork it will have a try. I can test it with my daughter 😜

**Comment by volkerrichert** [comment]
ok. I'm not sure if alarm & urgenAlarm will be detected correctly. can you chech this also. Not only if it keep running.

**Comment by volkerrichert** [comment]
can you try branch "fix/10"?

**Comment by bfelizardo** [comment]
Danke! @volkerrichert I have updated the adapter with your version 0.11.6 and will report back how it works. At the moment it is running 😄

**Comment by volkerrichert** [comment]
Bitte. I'll take a look during the weekend.

**Comment by volkerrichert** [comment]
Hm, i have to find out how and when to deactivate both alarms... I haven't seen any disableing alamr message

**Comment by bfelizardo** [comment]
@volkerrichert the adapter is up and running since the update. It seems fixed. Thank you very much Let's observe it for few more days.

**Comment by volkerrichert** [comment]
@bfelizardo Do you have some logs with alarm enabled & disabled? My Log didn't catch one

**Comment by volkerrichert** [comment]
@bfelizardo I add some code to clear alarms. Can you  retest it?

**Comment by bfelizardo** [comment]
@volkerrichert this is what I get in the logs:

<img width="735" alt="Screenshot 2021-05-02 at 12 07 02" src="https://user-images.githubusercontent.com/28575392/116809614-bea4ff00-ab36-11eb-9bc3-458edc20921f.png">

**Comment by bfelizardo** [comment]
@volkerrichert Ok i can see your fix in 0.11.7 I will give it a try.

**Comment by bfelizardo** [comment]
@volkerrichert I see you have changed it to a debug message. Do you want me to send you the debugging messages from the log later on?

**Comment by volkerrichert** [comment]
@bfelizardo Update to 0.11.7 and take a look at alarms and if they will be cleared. Keep debug enabled, so i can see what's wrong, if something doesn't work.

**Comment by bfelizardo** [comment]
@volkerrichert I did the update at 12:15 CET and it works fine. The alarm entity seems to be working. I have been tracking it and it gets updates quite frequent. It changes from 'true' to 'false' and back to 'true' again. The adapter keeps up an does not terminate since your changes this already worked int version 0.11.6.

**Comment by volkerrichert** [comment]
THX
