### ISSUE TITLE
Nightscout iobroker adapter does not connect after Upgrading Nightsocut Server to 14.2.2

### ISSUE THREAD

**Issue by Bleiki68** [ioBroker/ioBroker.nightscout#14]
**Describe the bug**  
After upgrading the Nightscout Server to version 14.2.2 the io.broker adapter connects to the server but
shows an error, that no connection to device or service is possible

**Comment by Bleiki68** [comment]
I tested 3 older Versions of the Nightscout Server. 14.2.2 and 14.1. had both the same error or connection problem.
With the old version 13.0.1 it is working.

**Comment by obodeldog** [comment]
Yes, you are right. I have the same problem
